// Generated by CoffeeScript 1.4.0
(function() {
  var circleAttributes, circles, polyCrazy, polyData, polyGoneCrazy, polygon, polygonAttributes, polygons, svg1, svg2, svg3;

  polygon = function(sides, size, radius, center) {
    var angle, circle, i, points, x, y, _i;
    circle = 2 * Math.PI;
    angle = circle / sides;
    points = [];
    for (i = _i = 0; 0 <= sides ? _i <= sides : _i >= sides; i = 0 <= sides ? ++_i : --_i) {
      x = (Math.cos(angle * i) * size) + center[0];
      y = (Math.sin(angle * i) * size) + center[1];
      points[i] = {
        "x": x,
        "y": y,
        "r": radius
      };
    }
    return points;
  };

  polyGoneCrazy = function(sides, size, radius, center) {
    var angle, circle, i, points, random, x, y, _i;
    circle = 2 * Math.PI;
    angle = circle / sides;
    points = [];
    for (i = _i = 0; 0 <= sides ? _i <= sides : _i >= sides; i = 0 <= sides ? ++_i : --_i) {
      random = Math.floor(Math.random() * (size + 1));
      x = (Math.cos(angle * i) * random) + center[0];
      y = (Math.sin(angle * i) * random) + center[1];
      points[i] = {
        "x": x,
        "y": y,
        "r": radius
      };
    }
    return points;
  };

  polyData = polygon(6, 150, 20, [250, 250]);

  polyCrazy = polyGoneCrazy(100, 150, 20, [250, 250]);

  svg1 = d3.select("#experimental-circles-only").append("svg").attr("width", 500).attr("height", 500);

  circles = svg1.selectAll("circle").data(polyData).enter().append("circle").style("fill", "gray").style("stroke", "none").style("stroke-width", 2);

  circleAttributes = circles.attr("cx", function(d) {
    return d.x;
  }).attr("cy", function(d) {
    return d.y;
  }).attr("r", function(d) {
    return d.r;
  });

  svg2 = d3.select("#experimental-circles-polygon").append("svg").attr("width", 500).attr("height", 500);

  circles = svg2.selectAll("circle").data(polyData).enter().append("circle").style("fill", "gray").style("stroke", "none").style("stroke-width", 1);

  circleAttributes = circles.attr("cx", function(d) {
    return d.x;
  }).attr("cy", function(d) {
    return d.y;
  }).attr("r", function(d) {
    return d.r;
  });

  polygons = svg2.selectAll("polygon").data([polyData]).enter().append('polygon').style("stroke", "gray").style("stroke-width", 10).style("fill", 'none');

  polygonAttributes = polygons.attr("points", function(d) {
    return d.map(function(d) {
      return [d.x, d.y].join(",");
    }).join(" ");
  });

  svg3 = d3.select("#experimental-poly-gone-crazy").append("svg").attr("width", 500).attr("height", 500);

  polygons = svg3.selectAll("polygon").data([polyCrazy]).enter().append('polygon').style("stroke", "gray").style("stroke-width", 1).style("fill", 'gray');

  polygonAttributes = polygons.attr("points", function(d) {
    return d.map(function(d) {
      return [d.x, d.y].join(",");
    }).join(" ");
  });

}).call(this);
